name: create-release
on:
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish to pypi.org? (will not work from forks!)"
        required: false
        default: 'false'
jobs:
  create-release:
    name: Create new release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Publish to pypi
        uses: coveooss/pypi-publish-with-poetry@v2
        with:
          project-name: misp-stix
          pypi-token: ${{ secrets.PYPI_TOKEN }}
          pre-release: ${{ github.ref != 'refs/heads/main' }}
          dry-run: ${{ github.ref != 'refs/heads/main' && github.event.inputs.publish != 'true' }}
